site_name: PSTools

theme:
  name: material
  logo: images/lg.png
  favicon: images/favicon.ico
  custom_dir: mkdocs-overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.action.edit
    - content.action.view
  font:
    text: Fira Sans
    code: Fira Code
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - admonition
  - meta

repo_name: G2ft/PSTools
repo_url: https://github.com/G2ft/PSTools

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/G2ft/PSTools
